# Generated by Django 6.0.2 on 2026-04-10 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_remove_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itinerary.city'),
        ),
    ]
