# Generated by Django 6.0.2 on 2026-04-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0005_remove_activity_icon_activity_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
