# Generated by Django 5.2.12 on 2026-04-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_aquisition', '0002_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
    ]
